import type { Brances } from "@/table-types/brances";

export const branchData: Brances[] = [
  {
    id: "1",
    districtId: "Guwahati",
    branceName: "Guwahati Central",
    email: "central.guwahati@abc.com",
    password: "Pass@123",
    remarks: "Main branch",
  },
  {
    id: "2",
    districtId: "Guwahati",
    branceName: "Guwahati East",
    email: "east.guwahati@abc.com",
    password: "East@123",
    remarks: "Popular zone",
  },
  {
    id: "3",
    districtId: "Jorhat",
    branceName: "Jorhat Town",
    email: "town.jorhat@abc.com",
    password: "Jorhat@123",
    remarks: "Busy area",
  },
  {
    id: "4",
    districtId: "Dibrugarh",
    branceName: "Dibrugarh North",
    email: "north.dibrugarh@abc.com",
    password: "Dibrugarh@123",
    remarks: "Newly opened",
  },
  {
    id: "5",
    districtId: "Dibrugarh",
    branceName: "Dibrugarh South",
    email: "south.dibrugarh@abc.com",
    password: "South@123",
    remarks: "High student flow",
  },
  {
    id: "6",
    districtId: "Tinsukia",
    branceName: "Tinsukia Main",
    email: "main.tinsukia@abc.com",
    password: "Tinsukia@123",
    remarks: "Old branch",
  },
  {
    id: "7",
    districtId: "Silchar",
    branceName: "Silchar West",
    email: "west.silchar@abc.com",
    password: "Silchar@123",
    remarks: "Premium zone",
  },
  {
    id: "8",
    districtId: "Tezpur",
    branceName: "Tezpur College Road",
    email: "college.tezpur@abc.com",
    password: "Tezpur@123",
    remarks: "Near universities",
  },
  {
    id: "9",
    districtId: "Nagaon",
    branceName: "Nagaon Central",
    email: "central.nagaon@abc.com",
    password: "Nagaon@123",
    remarks: "Very active",
  },
  {
    id: "10",
    districtId: "Sivasagar",
    branceName: "Sivasagar City",
    email: "city.sivasagar@abc.com",
    password: "Siva@123",
    remarks: "Good rating",
  },
];
